# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canary < Formula
  desc "Pixel-art fatigue bird for your shell prompt and Claude Code's status line"
  homepage "https://github.com/thousandflowers/canary"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thousandflowers/canary/releases/download/v1.1.0/canary_darwin_amd64.tar.gz"
      sha256 "c6a3994c30c2d07bcdebc9828b44fabf4b64d122fc2d904734425247f21e401b"

      define_method(:install) do
        bin.install "canary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thousandflowers/canary/releases/download/v1.1.0/canary_darwin_arm64.tar.gz"
      sha256 "86efd41e6ef41a9867af308b25919832c408f462356f741e3fb2521b4cac27c5"

      define_method(:install) do
        bin.install "canary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thousandflowers/canary/releases/download/v1.1.0/canary_linux_amd64.tar.gz"
      sha256 "2baefef369ac5daf0456d1d41c366928cbf4564d9ab29f21e0aee41f3adbb73f"
      define_method(:install) do
        bin.install "canary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thousandflowers/canary/releases/download/v1.1.0/canary_linux_arm64.tar.gz"
      sha256 "89e76f97813561d8f554f80c98dc154960dac2a9a87134911401a49673a45419"
      define_method(:install) do
        bin.install "canary"
      end
    end
  end

  def caveats
    <<~EOS
      canary is two birds from one binary: one above your shell prompt, one in
      Claude Code's status line.

      Wire your shell (zsh, bash or fish) by adding this to your rc file:

        eval "$(canary init zsh)"          # fish: canary init fish | source

      And the Claude Code status line:

        canary settings install

      Open a new shell, and restart Claude Code, to meet them. Tame with
      CANARY_DISABLED, CANARY_MIN_SCORE (71 = only once it matters),
      CANARY_SHOW_SCORE, CANARY_QUIET — see README.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/canary version")

    # The corpus is compiled into the binary. Asserting a file exists is not
    # the same assertion, and the weaker one is what let v0.7.0 nearly ship
    # with the phrase system inert.
    assert_match "the canary is quiet.",
                 shell_output("#{bin}/canary preview --state dead")

    # Hermetic Claude Code mode: an empty transcript fixture, and every state
    # file pointed at testpath so this never reads the *tester's* real
    # ~/.canary/history — which would make the assertion depend on how tired
    # the person running brew test happens to be.
    transcript = testpath/"transcript.jsonl"
    transcript.write("")
    input = %Q({"cost":{"total_duration_ms":0},"transcript_path":"#{transcript}"})
    cmd = "CANARY_HISTORY_FILE=#{testpath}/history CANARY_STATE_FILE=#{testpath}/state " \
          "CANARY_PHRASE_STATE=#{testpath}/phrase-state #{bin}/canary statusline"
    assert_match "fresh", pipe_output(cmd, input)

    # And the prompt bird scores a session it has just been told about.
    system bin/"canary", "record", "--", "git status"
    assert_match "▐ O ▌>",
                 shell_output("CANARY_NIGHT_MULT=100 #{bin}/canary status")
  end
end
