# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canary < Formula
  desc "Pixel-art fatigue bird for your shell prompt and Claude Code's status line"
  homepage "https://github.com/thousandflowers/canary"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thousandflowers/canary/releases/download/v1.0.0/canary_darwin_amd64.tar.gz"
      sha256 "1bc0d6426c885d6329545474650ecb1e83d458f5f25e796bb83912fb42623902"

      define_method(:install) do
        bin.install "canary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thousandflowers/canary/releases/download/v1.0.0/canary_darwin_arm64.tar.gz"
      sha256 "322b7f73bc8f1f0fc77c75cc65bc110929ef37ff452fb8e5cb0dea5e72fea3d0"

      define_method(:install) do
        bin.install "canary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thousandflowers/canary/releases/download/v1.0.0/canary_linux_amd64.tar.gz"
      sha256 "7b69856060fd9d428fa27fee3b2ba0e6ec36a2f9e24d5710581dc27b8836f56b"
      define_method(:install) do
        bin.install "canary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thousandflowers/canary/releases/download/v1.0.0/canary_linux_arm64.tar.gz"
      sha256 "d8ee0599ee44c487c8d0cbc6862f16e84bf535bc7b4b6f58a39d87bc9528805b"
      define_method(:install) do
        bin.install "canary"
      end
    end
  end

  def caveats
    <<~EOS
      canary is two birds from one binary: one above your shell prompt, one in
      Claude Code's status line.

      Wire your shell (zsh, bash or fish) by adding this to your rc file:

        eval "$(canary init zsh)"          # fish: canary init fish | source

      And the Claude Code status line:

        canary settings install

      Open a new shell, and restart Claude Code, to meet them. Tame with
      CANARY_DISABLED, CANARY_MIN_SCORE (71 = only once it matters),
      CANARY_SHOW_SCORE, CANARY_QUIET — see README.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/canary version")

    # The corpus is compiled into the binary. Asserting a file exists is not
    # the same assertion, and the weaker one is what let v0.7.0 nearly ship
    # with the phrase system inert.
    assert_match "the canary is quiet.",
                 shell_output("#{bin}/canary preview --state dead")

    # Hermetic Claude Code mode: an empty transcript fixture, and every state
    # file pointed at testpath so this never reads the *tester's* real
    # ~/.canary/history — which would make the assertion depend on how tired
    # the person running brew test happens to be.
    transcript = testpath/"transcript.jsonl"
    transcript.write("")
    input = %Q({"cost":{"total_duration_ms":0},"transcript_path":"#{transcript}"})
    cmd = "CANARY_HISTORY_FILE=#{testpath}/history CANARY_STATE_FILE=#{testpath}/state " \
          "CANARY_PHRASE_STATE=#{testpath}/phrase-state #{bin}/canary statusline"
    assert_match "fresh", pipe_output(cmd, input)

    # And the prompt bird scores a session it has just been told about.
    system bin/"canary", "record", "--", "git status"
    assert_match "▐ O ▌>",
                 shell_output("CANARY_NIGHT_MULT=100 #{bin}/canary status")
  end
end
